name: Inspect .tool-versions
description: Inspects the .tool-versions file and returns the tools and versions contained within.
inputs:
  filename:
    description: "Filename for the .tool-versions file"
    required: false
    default: ".tool-versions"
  tool:
    description: 'Name of the tool (e.g. "terraform") to query'
    required: true
outputs:
  version:
    description: "Version of the tool"
    value: ${{ steps.inspect.outputs.version}}
runs:
  using: "composite"
  steps:
    - name: Inspect tool version
      id: inspect
      shell: bash
      run: |
        TOOL_VERSION_FILENAME=${{ input.filename }}
        TOOL=${{ input.tool }}

        stat $TOOL_VERSION_FILENAME || (echo "::error file=$TOOL_VERSION_FILENAME,title=Failed to locate .tool-versions file::Tool versions file at $TOOL_VERSION_FILENAME did not exist!"; exit 1)
        VERSION=$(grep $TOOL $TOOL_VERSION_FILENAME | cut -d ' ' -f 2)
        test -z $VERSION && (echo "::error file=$TOOL_VERSION_FILENAME,title=Tool version not found::Tool versions file at $TOOL_VERSION_FILENAME did not contain a version for tool $TOOL!"; exit 1)
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
